- include/grabber/V4L2Worker.h
- libsrc/grabber/v4l2/V4L2Worker.cpp
Apply changes & optimization from YUV part to MJPEG decoding.
> apply optimization for MJPEG LUT operation from YUV code part

- assets/webconfig/i18n/en.json
- include/flatbufserver/FlatBufferConnection.h
- include/flatbufserver/FlatBufferServer.h
- sources/api/API.cpp
- sources/flatbufserver/FlatBufferClient.cpp
- sources/flatbufserver/FlatBufferClient.h
- sources/flatbufserver/FlatBufferConnection.cpp
- sources/flatbufserver/FlatBufferServer.cpp
- sources/hyperhdr/hyperhdr.cpp
- sources/hyperhdrbase/MessageForwarder.cpp
- sources/hyperhdrbase/schema/schema-flatbufServer.json
**Summary**
Introduces HDR tone mapping for flatbuffers input.
In some cases (depending on TV modell / capturing library in use) [PicCap](https://github.com/TBSniller/piccap) (Hyperion Sender App on LG TVs) is sending dim/pale images when HDR/Dolby Vision content is playing. Tone mapping helps to get this image data back to "normal".
Before:
After:
If yes, please describe the impact and migration path for existing setups:
**The PR fulfills these requirements:**
If adding a **new feature**, the PR's description includes:
**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO …
> HDR tone mapping for flatbuffers

- assets/webconfig/content/json_api.html
- assets/webconfig/i18n/en.json
- assets/webconfig/js/json_api.js
- include/api/API.h
- include/flatbufserver/FlatBufferServer.h
- sources/api/API.cpp
- sources/api/JSONRPC_schema/schema-videomodehdr.json
- sources/api/JsonAPI.cpp
- sources/flatbufserver/FlatBufferServer.cpp
The JSON API for controlling tone mapping has been extended to include an optional LUT file name for FlatBuffers.
This allows to select proper LUT for tone mapping depending on the external video properties.
For example you can have two or more LUT files for selection: one for SDR, one for HDR, one for DV etc.
HyperHDR expects that these files are located in HyperHDR home folder e.g. /home/pi/.hyperhdr
- [ x] Feature
- [ x] No
> Flatbuffers: selectable custom LUT files

- sources/grabber/MF/MFWorker.cpp
- sources/grabber/v4l2/V4L2Worker.cpp
ZasLuke grabber is using non-standard low quality codec TJSAMP_420 for MJPEG and tone mapping since v18 supported only popular TJSAMP_422 mode. But the encoding of TJSAMP_420 appears to be identical to already supported I420. This PR brings back tone mapping for MJPEG stream for ZasLuke grabber.
Reported here: https://github.com/awawa-dev/HyperHDR/discussions/323
> Add ZasLuke Capture card support for MJPEG tone mapping

- assets/webconfig/js/ui_utils.js
- include/base/HyperHdrIManager.h
- sources/base/HyperHdrIManager.cpp
- sources/hyperhdr/hyperhdr.cpp
- sources/hyperhdr/hyperhdr.h
Currently, the start of the http & https webserver was not synchronized with the start of the proper instance. This led to non-critical deadlocks when the HyperHDR website was opened by the user and the HyperHDR was restarted at the same time. After reloading the page, it was also possible to select the wrong instance. The patch synchronizes the start of the web server when the instance is ready for use.
> Improved HyperHDR web server startup

- .ci/ci_build.sh
- .github/workflows/push-master.yml
- sources/flatbufserver/FlatBufferConnection.cpp
- sources/hyperhdr/CMakeLists.txt
Updated Github Action runner to macos-12 as 10.15 will be deprecated soon.
To maintain backward binary compatibility with macOS 10.15, QT must be downgraded to 5.15, because of brew repository is targeting QT6@macos-12 using newer system framework.
> Github Action: upgrade runner to macos-12

- sources/base/DetectionAutomatic.cpp
If the 'signal lost detection' is triggered by a frame, but next frames don't confirm it and cancel the event, then after some time next single frame that matches no-signal board can trigger no-signal event immediately (ignoring Automatic Detection 'Sleep time' settings).
A similar situation happens when waking-procedure (on signal restored) is interrupted, then the next single frame can wake up HyperHDR immediately (ignoring Automatic Detection 'Wake time' settings).
Usually can happen for noisy input when the HyperHDR was calibrated for black no-signal board. So single black video frames could sudden trigger false 'no-signal' event.
> Fix: Automatic signal detection timing

- assets/webconfig/js/light_source.js
- include/base/ImageToLedsMap.h
- include/base/LedString.h
- sources/base/HyperHdrInstance.cpp
- sources/base/ImageToLedsMap.cpp
- sources/base/LedString.cpp
- sources/base/LinearSmoothing.cpp
Fix some issues related to disabled leds
1) LED post processing/color calibration could override the black color (e.g. 'Backlight threshold')
2) JSONACEEditor schema not updated to include new "disabled" property causing errors when manually editing
Fixes  #418
> Fix disabled leds

- sources/base/schema/schema-color.json
- sources/grabber/v4l2/V4L2Grabber.cpp
Add support for old analog grabber utv007. To control old analog switches like PAL/SECAM standard use ```v4l2-ctl``` (-s parameter, the capturing must be stopped before) Linux command. For example:  
`sudo systemctl stop hyperhdr@pi && v4l2-ctl -s pal-B && sudo systemctl start hyperhdr@pi`
**Resolution 720x576 is for PAL only. Otherwise you may encounter problems when capturing NTSC standard.**
Fixes #422 
Fixes #421
> Add support for utv007 / Linux

- .github/workflows/image-builder-from-repo.yml
- sources/leddevice/dev_serial/EspTools.h
- sources/leddevice/dev_serial/LedDeviceAdalight.cpp
- sources/leddevice/dev_serial/ProviderRs232.cpp
- sources/leddevice/dev_serial/ProviderRs232.h
- sources/leddevice/dev_spi/LedDeviceAWA_spi.cpp
Add support for esp32-s2 mini CDC board 'esp8266/esp32 handshake' in the Adalight driver properties. Needs firmware HyperSerialESP32 v8 (https://github.com/awawa-dev/HyperSerialESP32/pull/10)
> ESP32-S2 mini support (Adalight AWA protocol)

- sources/leddevice/dev_serial/EspTools.h
Use longer reset pulse to make sure that esp is completely reseted
Fixes https://github.com/awawa-dev/HyperSerialESP32/issues/13
If yes, please describe the impact and migration path for existing setups:
**The PR fulfills these requirements:**
If adding a **new feature**, the PR's description includes:
**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.
**Other information:**
> Use longer reset pulse

- sources/leddevice/dev_serial/ProviderRs232.cpp
- sources/leddevice/schemas/schema-adalight.json
If `ESP32/Esp8266 handshake` is enabled and the user selects 'auto' in the device selection, HyperHDR will search for known ESP devices in the first place. 
Serial port re-discovery is triggered now every time the device is started for such configuration.
Auto resume mechanism can be enabled now for the Adalight.
> Adalight: auto-resume and ESP8266/ESP32 auto-discovery

- sources/leddevice/dev_net/LedDeviceUdpRaw.cpp
- sources/leddevice/dev_net/LedDeviceWled.cpp
Fix wled/udpraw proper buffer size when LED number has been changed in the current session.
Fixes #562
> Fix for #562

- sources/leddevice/dev_serial/EspTools.h
There is currently a critical bug in the udev module that causes serial devices to be misidentified.
Affects HyperSerial8266/HyperSerialESP32/HyperSerialPico devices especially using Raspberry Pi OS arm64 with kernel 6.
HyperHDR SD v19 images work fine if the system is not updated.
This PR provides a workaround on Rpi4 for 'esp8266/esp32/rp2040 handshake' in the Adalight driver until it is fixed in the upstream.
Automatic device detection will not work, so the correct path for the serial device must be manually selected from the list.
Read more:
1) https://bugreports.qt.io/browse/QTBUG-113462
2) https://github.com/awawa-dev/HyperHDR/discussions/561#discussioncomment-5994170
> Workaround for Rpi udev critical bug

- sources/mqtt/mqtt.cpp
Currently one mqtt client requires an ip address. However, often we want to use hostname instead. This change should account for that
**Summary**
If yes, please describe the impact and migration path for existing setups:
**The PR fulfills these requirements:**
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.
**Other information:**
> Added hostname resolution

- include/utils/Logger.h
- sources/hyperhdr/main.cpp
- sources/utils/Logger.cpp
Let's have colorful logs when HyperHDR is run on the console. Just like HyperHDR logs in the webpage are colorful.
This makes it much easier to spot errors and warnings (and they are more pleasant and readable).
Works on Linux (console terminal) and Windows (hyperhdr.exe with -c parameter).
> Colorized logs

- .github/workflows/push-master.yml
- .github/workflows/upload-to-github-pages.yml
Upgrade:
Fedora 38 to 39 (for release build and Github Action)
Ubuntu 23.04 to 23.10 (for release build)
> Upgrade Fedora 38 to 39, Ubuntu 23.04 to 23.10

- .github/workflows/push-master.yml
Installing brew packages causing Github macOS runner azure-cli to trigger install Python that fails. Both packages are not used by HyperHDR.
> Workaround for Github macOS runner bug

- .github/workflows/push-master.yml
Another workaround for Github `macos-latest` runner image that currently is in a messy state causing the build to randomly fail
https://github.com/actions/runner-images/issues/8838
https://github.com/actions/runner-images/issues/8529
https://github.com/actions/runner-images/issues/8642
and many others...
> Github macos-latest runner workaround

- .github/workflows/push-master.yml
- sources/grabber/pipewire/PipewireHandler.cpp
**Summary**
When this parameter is enabled than pipewire reports the following error:
**HyperHDR:**
Pipewire: updated parameters 0
Pipewire: core error reported
Pipewire: stream reports error 'error alloc buffers: Invalid argument' Pipewire: core reports error 'error alloc buffers: Invalid argument'
**Pipewire:**
pipewire[1850759]: pw.context: params Spa:Enum:ParamId:Buffers: 1:0 Invalid argument (input param) pipewire[1850759]: pw.context: Object: size 168, type Spa:Pod:Object:Param:Buffers (262148), id Spa:Enum:ParamId:Buffers (5)
pipewire[1850759]: pw.context:   Prop: key Spa:Pod:Object:Param:Buffers:BlockInfo:size (3), flags 00000000
pipewire[1850759]: pw.context:     Int 33177600
pipewire[1850759]: pw.context:   Prop: key Spa:Pod:Object:Param:Buffers:buffers (1), flags 00000000 …
> fix pipewire portal by removing blocks parameter

- include/base/ComponentController.h
- include/base/HyperHdrInstance.h
- include/base/HyperHdrManager.h
- include/leddevice/LedDevice.h
- include/leddevice/LedDeviceWrapper.h
- sources/base/ComponentController.cpp
- sources/base/HyperHdrInstance.cpp
- sources/base/HyperHdrManager.cpp
- sources/base/schema/schema-general.json
- sources/grabber/DX/DxGrabber.cpp
- sources/hyperhdr/HyperHdrDaemon.cpp
- sources/hyperhdr/HyperHdrDaemon.h
- sources/hyperhdr/SuspendHandlerLinux.cpp
- sources/hyperhdr/SuspendHandlerLinux.h
- sources/hyperhdr/SuspendHandlerMacOS.h
- sources/hyperhdr/SuspendHandlerMacOS.mm
- sources/hyperhdr/SuspendHandlerWindows.cpp
- sources/hyperhdr/SuspendHandlerWindows.h
- sources/leddevice/LedDevice.cpp
- sources/leddevice/LedDeviceWrapper.cpp
- www/i18n/en.json
- www/js/general.js
1 If user has locked the Win system, for example using windows + L keys, HyperHDR stops processing and turns off the LEDs.
It resumes when the user unlock the system. Fixes #735
2 Added an option that cause HyperHDR not to turn on LEDs when starts up. Implements #627
> New features: disable LEDs/components on startup, stop processing when user has locked the system

- .github/workflows/push-master.yml
- include/base/ComponentController.h
- include/base/HyperHdrInstance.h
- include/base/HyperHdrManager.h
- include/utils/Components.h
- sources/base/ComponentController.cpp
- sources/base/HyperHdrInstance.cpp
- sources/base/HyperHdrManager.cpp
- sources/blackborder/BlackBorderDetector.cpp
- sources/hyperhdr/SuspendHandlerLinux.cpp
- sources/hyperhdr/SuspendHandlerLinux.h
- sources/hyperhdr/SuspendHandlerMacOS.h
- sources/hyperhdr/SuspendHandlerMacOS.mm
- sources/hyperhdr/SuspendHandlerWindows.cpp
- sources/hyperhdr/SuspendHandlerWindows.h
The first batch of changes was introduced in this PR: https://github.com/awawa-dev/HyperHDR/pull/737
Now the functionality of turning off/waking up HyperHDR when the system is locked has been extended (Windows):
- if the background effect is set, the LEDs are not turned off, the effect works despite the system being locked, but the USB grabber and the system grabber are turned off to reduce the resource load
- if an OS event about the monitor turning off is detected, the same behavior occurs as when the system is locked (possibly turning off the LEDs and grabbers or resuming them later).
HyperHDR returns to its original state after unlocking the system or turning the monitor back on.
> Enhanced HyperHDR behavior when the system is locked or the monitor is turned off

- CHANGELOG.md
- sources/leddevice/LedDevice.cpp
- sources/leddevice/dev_net/LedDeviceYeelight.cpp
- sources/leddevice/dev_net/LedDeviceYeelight.h
- sources/leddevice/schemas/schema-yeelight.json
- www/js/wizard.js
**Summary**
If yes, please describe the impact and migration path for existing setups:
**The PR fulfills these requirements:**
To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.
**Other information:**
> Added Wizard Support for more Yeelight products, and workaround for music-mode reset by some of them. (Fixes: #748)

- .github/actions/codeql/action.yml
- CHANGELOG.md
- sources/effectengine/AnimationBaseMusic.cpp
- sources/effectengine/Effect.cpp
If a background music effect is set, it may prevent the HyperHDR web interface from starting and working properly.
Fixes #760
> Fix background music effect

- sources/base/Grabber.cpp
- sources/flatbufserver/FlatBufferServer.cpp
When loading the LUT, memory was unnecessarily allocated to the entire 144MB LUT file instead of the selected 48MB sub-table. The fix reduces HyperHDR memory consumption by 96MB if a LUT was used (including YUV to RGB also in SDR, HDR tone mapping in USB grabbers or flatbuffers/protobuffers when full 144MB LUT table was used)
> Fix critical LUt memory bug

- .github/workflows/push-master.yml
- .gitmodules
Due to CVE-2024-3094 XZ repo from Github was removed and currently the build process fails.
Switched to the original XZ repo and the older branch until everything clears up.
HyperHDR used the older version 5.4.3 as a submodule (basically only for Windows, as it tried to use system libraries otherwise), so this had no effect, since the attack on Linux was performed on versions 5.6.0-5.6.1 in February  (has never arrived for Debian/Ubuntu/Fedora stable versions anyway). Also, the HyperHDR only release for rolling distro (Arch Linux) was built on docker from 19 January, also before the attack, and uses version 5.4.6.
> Switch xz to tukaani repo

- include/base/Grabber.h
- include/flatbuffers/parser/FlatBuffersParser.h
- include/flatbuffers/parser/hyperhdr_request.fbs
- include/flatbuffers/server/FlatBuffersServer.h
- include/flatbuffers/server/FlatBuffersServerConnection.h
- include/image/ColorRgb.h
- include/utils/FrameDecoder.h
- include/utils/LutLoader.h
- sources/base/Grabber.cpp
- sources/flatbuffers/parser/FlatBuffersParser.cpp
- sources/flatbuffers/server/FlatBuffersServer.cpp
- sources/flatbuffers/server/FlatBuffersServerConnection.cpp
- sources/grabber/linux/v4l2/V4L2Grabber.cpp
- sources/grabber/linux/v4l2/V4L2Worker.cpp
- sources/grabber/osx/AVF/AVFGrabber.mm
- sources/grabber/osx/AVF/AVFWorker.cpp
- sources/grabber/windows/DX/DxGrabber.cpp
- sources/grabber/windows/MF/MFGrabber.cpp
- sources/grabber/windows/MF/MFWorker.cpp
- sources/lut-calibrator/LutCalibrator.cpp
- sources/utils/FrameDecoder.cpp
- sources/utils/LutLoader.cpp
Till recently HyperHDR flatbuffers server only supported raw RGB format. It had many limitation.
But thanks to @s1mptom for inspiration this PR adds NV12 image format to HyperHDR flatbuffers server (more discussion here: https://github.com/awawa-dev/HyperHDR/discussions/916) For now you can use it with rather exotic and unsupported here webos capturing application but it is intended to work with any client and in the future it will be easy to extend it to other formats such as mjpeg
Advantages:
- NV12 YUV conversion was completely moved to HyperHDR which uses LUT table for this purpose (zero calculations when converting YUV to RGB). Using selected LUT it can also perform YUV to RGB conversion and tone mapping in the same one step. This means we reduce the client load because in addition …
> Add NV12 image format support for flatbuffers!

- sources/led-strip/LedCalibration.cpp
When trying to set the LED color option, e.g. luminance gain, in the case of having several configuration sections, it was always set first despite passing the identifier to another section.
This PR fixes: #953
> Fix LED colors adjustments by configuration name

- sources/grabber/windows/DX/DxGrabber.cpp
Resolves #779 , enables auto-retry if the device is currently not present
> DX grabber: stick to user specified device selection

- include/bonjour/DiscoveryRecord.h
- include/bonjour/DiscoveryWrapper.h
- include/led-drivers/net/DriverNetHomeAssistant.h
- sources/api/HyperAPI.cpp
- sources/api/JSONRPC_schema/schema-tunnel.json
- sources/bonjour/BonjourServiceHelper.cpp
- sources/bonjour/BonjourServiceRegister.cpp
- sources/bonjour/DiscoveryRecord.cpp
- sources/bonjour/DiscoveryWrapper.cpp
- sources/led-drivers/CMakeLists.txt
- sources/led-drivers/LedDeviceSchemas.qrc
- sources/led-drivers/net/DriverNetHomeAssistant.cpp
- sources/led-drivers/schemas/schema-home_assistant.json
- sources/led-drivers/schemas/schema-skydimo.json
- www/i18n/en.json
- www/js/hyperhdr.js
- www/js/light_source.js
- www/js/wizard.js
Work is finished:
- Added mDNS scan for HomeAssistant instances
- Web wizards including scanning of devices & lamps capabilities
- Support for dynamic and constant brightness
- Support for RGB and HSL model
- Support for saving & restoring state of lamps
Implements #918 
I assume you've already configured your lights in Home Assistant. The photo below shows Philips Hue lights connected via a ZigBee adapter.
<a href="https://github.com/user-attachments/assets/53de8fa8-67dd-4989-bc8e-784697b09650"><img src="https://github.com/user-attachments/assets/53de8fa8-67dd-4989-bc8e-784697b09650" width="80%" /></a><br/>
If the lights work properly in Home Assistant, you need to create one more thing necessary to support them in HyperHDR: `Long Lived Access Token`.
You will find the required option in …
> Add support for Home Assistant lights

- include/base/Grabber.h
- include/led-strip/ChannelCalibration.h
- sources/base/Grabber.cpp
- sources/base/SystemWrapper.cpp
- sources/base/schema/schema-systemGrabber.json
- sources/grabber/windows/DX/DxGrabber.cpp
- sources/led-strip/ChannelCalibration.cpp
- sources/led-strip/ColorCalibration.cpp
- www/i18n/en.json
Just increase re-order mode till you get correct order in the video live preview
> Feature to re-order displays in multi-display mode (DirectX)

- .github/workflows/push-master.yml
- .github/workflows/upload-to-github-pages.yml
Switch qemu arm runners to native arm runners.
Finally Github allows us to use them!  https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
> Switch to Github Arm runners

- external/CMakeLists.txt
> Update LunaSVG to v3.1.0

- .github/workflows/push-master.yml
Fixes aqtinstall bug when using default Github Action runner Python 3.9 on Windows.
> Windows GA: temporary workaround for aqtinstall=>Python3.13

- sources/grabber/windows/DX/DxGrabber.cpp
Adds portrait mode support (display rotated by 90/270 degrees) in Windows DirectX11 grabber.
Implements #1199
> DX grabber: portrait mode support

- cmake/installers.cmake
- sources/api/HyperAPI.cpp
- sources/led-drivers/net/DriverNetPhilipsHue.cpp
- www/js/wizard.js
There was a conflict between OpenSSL1.1 and OpenSSL 3 and an incorrect R_PATH variable in the libraries included with the macOS installer, which leads in HyperHDR to incorrect operation of the https protocol, including HyperHDR https instance and some network LED drivers ex. for Philips Hue devices.
Also fixed accreditation creation for Philips Hue Bridge Pro
This PR fixes the issues #1289 #1285
> Fix for OpenSSL on macOS (needed by https/tls)
